name: Feather In The Wind
favicon: null
layout_spectrum: 0.25425
typography_spectrum: 0.8111376948654652
title: Come fly with me.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e5de'
    - '#424853'
    - '#98afbd'
    - '#479453'
    - '#78d36a'
  brandStrength: 0.955796763766557
  lightness: 0.47346017020754516
  saturation: 0.6129950270988047
  rhythmicContrast: 0.322638425976038
purpose: []
