name: Feather In The Wind
favicon: null
layout_spectrum: 0.76628
typography_spectrum: 0.49042
title: Feather In The Wind
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1a1a'
    - '#444444'
    - '#a0a0a0'
    - '#787878'
  brandStrength: 0.5
  lightness: 0.47346017020754516
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
